name: Fetch NYT Wordle Answer


permissions:
  contents: write

on:
  schedule:
    - cron: "5 0 * * *"  # Runs daily at 00:05 UTC
  workflow_dispatch:      # Allows manual run

jobs:
  update-wordle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install jq (for JSON parsing)
        run: sudo apt-get install jq -y

      - name: Fetch NYT Wordle JSON and extract solution
        run: |
          TODAY=$(date +'%Y-%m-%d')
          URL="https://www.nytimes.com/svc/wordle/v2/$TODAY.json"
          RAW_JSON=$(curl -s "$URL")
          SOLUTION=$(echo "$RAW_JSON" | jq -r '.solution')
          echo "{ \"solution\": \"$SOLUTION\" }" > daily-word.json

      - name: Commit & Push if Changed
        run: |
          git config user.name "Wordle Bot"
          git config user.email "actions@github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add daily-word.json
            git commit -m "Update Wordle solution for $TODAY"
            git push
          else
            echo "No changes to commit."
          fi
