name: Fetch NYT Wordle Answer


permissions:
  contents: write

on:
  schedule:
    - cron: "5 0 * * *"  # Runs daily at 00:05 UTC
  workflow_dispatch:      # Allows manual run

jobs:
  update-wordle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install jq (for JSON parsing)
        run: sudo apt-get install jq -y

      - name: Fetch NYT Wordle JSON and extract solution
        run: |
          TODAY=$(date +'%Y-%m-%d')
          URL="https://www.nytimes.com/svc/wordle/v2/$TODAY.json"
          RAW_JSON=$(curl -s "$URL")
          SOLUTION=$(echo "$RAW_JSON" | jq -r '.solution')
          echo "{ \"solution\": \"$SOLUTION\" }" > daily-word.json

      - name: Commit & Push if Changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Wordle Bot"
          git config user.email "actions@github.com"

          echo "Repo = ${{ github.repository }}"
          
          # Set token-authenticated remote
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
      
          # Pull latest changes and rebase
          git pull --rebase origin master || echo "Nothing to pull or rebase failed, continuing"
      
          # Stage and commit changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add daily-word.json
            git commit -m "Update Wordle solution for $(date +'%Y-%m-%d')"
            git push origin HEAD:master
          else
            echo "No changes to commit."
          fi
